apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekEwTVRZeApOVEkwTVRCYUZ3MDBNekEwTVRZeE5USTBNVEJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFERFB6NHVyTjJlQ29qRUt2MW5sR1pQbytHMUdRR2svY09xRzgvREVEaEd3YVlMK0p4UwozTFRXbnpSM291SVZ2TGUyZlZ2N3dnWmtWdElDUEo0YkVjZVJYQndiV1gvaFpVSDduZ2pWaGpvYlRvYmtHRWRyCjBwMlE5OE9VdGhEeTdoZXlBa1pGWUJyZ2RsUDVPei90OEZUSUFBWnlid1A3SHFyc1hCT1lKSTBNZ1F2Z09kenAKMzJxQnFSdXBNZUdBZkltVTg4MjByb2x1WGpQcm5Fb092a0Y4cnBINElRMmFidG42dFYrUVRPalV6VDFZc1RWMApWSTE3aXJQQnpwZ1lybjRVYXJkKzRlamV3WXduMjJlVmJjeHBYN0FNcUxPbTdDbWs1UkZ2RmpDRW41Q0FTNTRoCkhRMGkyckhFb2pXZGlRUUhFaGRIak42N3V0TE93VVg4aEp4REFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFUVVVGb0tvbVROTTlORmREeApndjRIR0RZM3VEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFqU3VLU1RyYTNqZ25SbzZrb2FLRXJaY3I5VGk1ClE3V2I2TFI0MGIrWFJNdzhmb0x2YUNBZEw2U3R2aUgvL1Q0YXM2dlZ4WWNqS0Eyckp4ZlJhSVY3L01kKzBTUWwKZ3U0aDBrQW1QUW9pekhWa3hmTXRTZndCUTdoTzk1OVQ0cGhoem5NbHpjVWtuRXZwTXZjc0FQOXNRN1ZsRElJSAovaEd3OWhQeU9CSDBRRWpPaTZtSFgwWGVabnNqZU1OWm5tNUFYNk1Dak1ObmlwMzU2NEFQNk0zSUNBdEJvY2NLCkVFK0g3VFFKMlRNOXBVNlpkaXhFNW5mM3REdUw2NHdkb2RESzJ0aVRpdjFFWXZWWGg3R2dzUE5VelUrSm9KOUsKMHZsTnMwVHhjZ2xhSEpJRFdWNnVYUDhYa01wUi9saHVKcXA1dlk1QnIxNmRBcEpvVzVFRkVNckRMQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://a5773ca6-dd2d-4d18-ab31-219628154208.k8s.ondigitalocean.com
  name: do-nyc1-k8s-aula
contexts:
- context:
    cluster: do-nyc1-k8s-aula
    user: do-nyc1-k8s-aula-admin
  name: do-nyc1-k8s-aula
current-context: do-nyc1-k8s-aula
kind: Config
preferences: {}
users:
- name: do-nyc1-k8s-aula-admin
  user:
    token: dop_v1_d95dcb0a1189d5c092a1b7837550643aa5380bfb96743f08569e7206f718a489
